### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by KiNgMaR** [m2osw/libaddr#1]
Hello there,

thanks for publishing this. LICENSE.txt looks like it's available under the MIT License, but the source code refers to the GNU GPL v2.

Can you please clarify which license the library is actually distributed under?

Thanks!
Ingmar

**Comment by AlexisWilke** [comment]
Ah. It's always hard to keep it straight. So many projects! I'll fix that one now. It should all be MIT for this library. It was part of the libsnapwebsites which is GPL 2.

**Comment by KiNgMaR** [comment]
Great, thanks! :+1:

**Comment by AlexisWilke** [comment]
Okay, it should be all clean now. I also fixed a few other files that needed help.
