### ISSUE TITLE
doc needed

### ISSUE THREAD

**Issue by darkr4y** [m2osw/libaddr#2]
how to compile or use it on windows?

**Comment by AlexisWilke** [comment]
@darkr4y Ah. This is a relatively new library and I have to say we did not even try to get it to work under Windows. I would suggest you write your own `CMakeLists.txt` or create a project and stick the files in there. However, the `#include` probably need some massage under MS-Windows. Also we may be using a few bits that are not available as is in `.NET`. (I assume you're not trying to compile under gnuwin or cygwin?)

The project as a whole ([snapcpp](https://snapwebsites.org/)) is not expected to be compiled under MS-Windows which is one of the main reasons we don't try to do that with each individual library.

Patches would be welcome.
